version: '3'

services:
  postgres:
    build: ./psql
    env_file: 
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - shared:/app/shared
    depends_on:
      - postgres
      - memcached
      - rabbitmq

  nginx:
    build: ./nginx
    volumes:
      - shared:/shared
    ports:
      - 80:80
    depends_on:
      - web
  
  memcached:
    image: memcached:1.5
    command: -m ${CACHE_SIZE}

  rabbitmq:
    image: rabbitmq:3.7
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASSWORD}
volumes:
  pgdata:
  shared: