version: '3'

services:
  postgres:
    build: ./psql

  web:
    build: .
    environment:
      WAIT_HOSTS: postgres:5432, memcached:11211
      ENV: DEV
      DB_HOST: postgres
      DB_PORT: 5432
      CACHE_HOST: memcached
      CACHE_PORT: 11211
    volumes:
      - ./src:/src
    ports:
      - "8080:8000"
    depends_on:
      - postgres
      - memcached
  
  memcached:
    image: memcached:1.5
    command: -m 128

  rabbitmq:
    image: rabbitmq:3.7
    environments:
      RABBITMQ_DEFAULT_USER: django_blog_user
      RABBITMQ_DEFAULT_PASS: password123