# Generated by Django 2.1.7 on 2019-03-23 09:55

import blog.utils
from django.db import migrations, models
import main.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.user_manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=blog.utils.UploadToFactory('main/profile/avatar'), verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=16, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='last_name'),
        ),
    ]
