# Generated by Django 2.1.7 on 2019-03-23 13:18

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallpaper',
            field=models.ImageField(default=1, upload_to=blog.utils.UploadToFactory('main/profile/wallpaper'), verbose_name='wallpaper'),
            preserve_default=False,
        ),
    ]
