# Generated by Django 2.1.7 on 2019-03-23 14:52

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallpaper',
            field=models.ImageField(null=True, upload_to=blog.utils.UploadToFactory('main/profile/wallpaper'), verbose_name='wallpaper'),
        ),
    ]
