# Generated by Django 2.1.7 on 2019-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190323_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=16, unique=True, verbose_name='title'),
        ),
    ]
