# Generated by Django 2.1.7 on 2019-04-14 12:04

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190414_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.IntegerField(db_index=True, default=time.time, editable=False, verbose_name='created at timestamp'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=16, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='last_name'),
        ),
    ]
