# Generated by Django 2.1.7 on 2019-04-16 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190415_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at datetime'),
            preserve_default=False,
        ),
    ]
