# Generated by Django 2.1.7 on 2019-04-16 05:36

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190416_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at2',
            field=models.IntegerField(db_index=True, default=time.time, editable=False, verbose_name='created at datetime'),
        ),
    ]
