# Generated by Django 2.1.7 on 2019-04-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190416_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at2',
            new_name='created_at',
        ),
    ]
