# Generated by Django 2.1.7 on 2019-04-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190416_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='birthday date'),
        ),
    ]
